parameters:

  ClusterIdPathParameter:
    name: cluster_id
    in: path
    required: true
    type: string
    description: Cluster ID

  UserEmailPathParameter:
    name: email
    in: path
    required: true
    type: string
    description: The user's email address

  OrganizationIdPathParameter:
    name: organization_id
    in: path
    required: true
    type: string
    description: |
        An ID for the organization.
        This ID must be unique and match this regular
        expression: ^[a-z0-9_]{4,30}$
