parameters:

  ClusterIdPathParameter:
    name: cluster_id
    in: path
    required: true
    type: string
    description: Cluster ID

  OrganizationIdPathParameter:
    name: organization_id
    in: path
    required: true
    type: string
    description: Organization ID
