parameters:

  ClusterIdPathParameter:
    name: cluster_id
    in: path
    required: true
    type: string
    description: Cluster ID

  OrganizationIdPathParameter:
    name: organization_id
    in: path
    required: true
    type: string
    description: |
        An ID for the organization to be created is the only required parameter.
        This ID can only contain alpha-numeric characters, hyphens, underscores, and dots.
