apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: api-spec
  namespace: docs
  labels:
    app: api-spec
  annotations:
    ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
  - host: api-spec.g8s.fra-1.giantswarm.io
    http:
      paths:
      - path: /
        backend:
          serviceName: api-spec
          servicePort: 8000
