apiVersion: v1
kind: Service
metadata:
  name: api-spec
  namespace: docs
  labels:
    app: api-spec
    repo: giantswarm/api-spec

spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: api-spec
