apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: api-spec-docserver
  namespace: giantswarm
  labels:
    app: api-spec-docserver

spec:
  replicas: 2

  template:
    metadata:
      labels:
        app: api-spec-docserver
    spec:
      containers:
      - name: api-spec-docserver
        image: registry.giantswarm.io/giantswarm/api-spec-docserver:%%DOCKER_TAG%%
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
      imagePullSecrets:
      - name: circleci-giantswarm-registry
